### ISSUE TITLE
第一届 PMCL管理委员会任命提要

### ISSUE THREAD

**Issue by xqzi** [xqzi/PMCL#6]
**2024年度 PMCL管理委员会 会长及副会长名额将在今日产生，**

**依照 发展决策 的相关条约要求，本年度贡献统计截止为今日 23:59。**

**当期作为项目起始的首期，因此很大可能出现名额将不足10名，**

**剩余名额将不做重新分配直至下一年度的管理委员会的任免产生。**

**空出的会长总票占比的决策权将由我(@xqzi )代为行使.**

**Comment by xqzi** [comment]
第一届  PMCL管理委员会 会长任命名单

依照 发展决策 的相关条约要求，第一届 PMCL管理委员会 会长由以下人员担任

@xsca
@MinecraftSTL 

- 以上两位会长的任期自 2024年1月1日 起至 2024年12月31日止，同时添加所有PMCL相关仓库的合作者身份(Collaborator)
- 希望通过各位的努力，在新的一年里给所有人带来欢乐。
- 最后祝各位新年快乐🎉

**Comment by xsca** [comment]
荣幸，荣幸！我会加油的。
